# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BayesianNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.DecimalField(decimal_places=6, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='RandomVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Framework')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Framework')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Framework')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Sentence'),
        ),
        migrations.AddField(
            model_name='bayesiannetwork',
            name='randomVariable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.RandomVariable'),
        ),
        migrations.AddField(
            model_name='assumption',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Framework'),
        ),
    ]
