# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assumption',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='bayesiannetwork',
            name='randomVariable',
        ),
        migrations.RemoveField(
            model_name='randomvariable',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='rule_head',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='framework',
        ),
        migrations.AddField(
            model_name='framework',
            name='string_representation',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Assumption',
        ),
        migrations.DeleteModel(
            name='BayesianNetwork',
        ),
        migrations.DeleteModel(
            name='RandomVariable',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
