# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0002_auto_20170517_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='string_representation',
            field=models.TextField(blank=True, default='.'),
        ),
    ]
