# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0004_dataset_datatick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatick',
            old_name='dataset_name',
            new_name='dataset',
        ),
    ]
