# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0005_auto_20170520_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_symbol', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('value', models.FloatField()),
                ('open_position', models.BooleanField()),
                ('framework_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Framework')),
            ],
        ),
        migrations.CreateModel(
            name='TradingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_trading', models.BooleanField()),
                ('trading_options', models.IntegerField(default=2)),
                ('required_trade_confidence', models.FloatField()),
                ('close_position_yield', models.FloatField()),
                ('close_position_loss_limit', models.FloatField()),
                ('framework_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Framework')),
            ],
        ),
    ]
