# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0007_auto_20170523_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='position_closed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='position_opened',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='enable_trading',
            field=models.BooleanField(default=True),
        ),
    ]
