# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0008_auto_20170525_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='value',
            new_name='price',
        ),
    ]
