# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0009_auto_20170525_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_price',
            field=models.FloatField(null=True),
        ),
    ]
