# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0010_trade_close_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.IntegerField(default=0),
        ),
    ]
