# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0012_auto_20170525_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatick',
            name='price',
            field=models.FloatField(),
        ),
    ]
