# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0013_auto_20170525_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='symbol',
            field=models.CharField(default=models.CharField(max_length=200), max_length=30),
        ),
    ]
