# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0015_auto_20170525_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='symbol',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
