# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0016_auto_20170525_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='buy_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='sell_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
