# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0017_auto_20170527_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatick',
            old_name='price',
            new_name='ask_price',
        ),
        migrations.AddField(
            model_name='datatick',
            name='bid_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
