# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0018_auto_20170529_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('symbol', models.CharField(default='', max_length=30)),
                ('string_representation', models.TextField(blank=True, default='.')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(default='', max_length=30)),
                ('framework', models.TextField(blank=True, default='.')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Market')),
            ],
        ),
        migrations.RemoveField(
            model_name='trade',
            name='framework_name',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='framework_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.User'),
        ),
        migrations.AddField(
            model_name='trade',
            name='market',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='babaApp.Market'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='strategy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='babaApp.Strategy'),
            preserve_default=False,
        ),
    ]
