# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0020_auto_20170531_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='market',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='babaApp.Market'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='market',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='babaApp.Market'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='strategy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='babaApp.Strategy'),
            preserve_default=False,
        ),
    ]
