# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0024_auto_20170601_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='position_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='position_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
