# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0025_auto_20170601_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_symbol', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('direction', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('open_position', models.BooleanField()),
                ('position_opened', models.DateTimeField(blank=True, null=True)),
                ('position_closed', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babaApp.Strategy')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='babaApp.User')),
            ],
        ),
    ]
