# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0026_simulatedtrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='string_representation',
        ),
    ]
