# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0027_remove_market_string_representation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='market',
            name='market_name',
            field=models.CharField(max_length=50),
        ),
    ]
