# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0031_auto_20170622_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='framework_extension',
            field=models.TextField(default=' '),
        ),
    ]
