# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaApp', '0033_auto_20170622_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='framework_at_close',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='trade',
            name='framework_at_open',
            field=models.TextField(default='.'),
        ),
    ]
